import {
  TbLayoutDashboard,
  TbDeviceGamepad2,
  TbSettings,
  TbPhoto,
  TbSlideshow,
  TbHeartHandshake,
  TbUsersGroup,
  TbPlayerPlay,
  TbNews,
  TbFileTypePdf,
  TbHierarchy,
  TbCreditCard,
  TbWallet,
  TbUsers,
  TbMapPin,
  TbKey,
} from "react-icons/tb";
import { FaRegUser } from "react-icons/fa";

const AdminSidebarItems = [
  {
    key: "dashboard",
    label: "Dashboard",
    heading: "Dashboard",
    path: "/admin/dashboard",
    icon: <TbLayoutDashboard size={18} />,
  },
  {
    key: "settings",
    label: "Settings",
    heading: "Settings",
    icon: <TbSettings size={18} />,
    children: [
      {
        key: "application-settings",
        label: "Application Settings",
        heading: "Application Settings",
        path: "/admin/application-settings",
        icon: <TbSettings size={18} />,
      },
      {
        key: "wallet-settings",
        label: "Wallet Settings",
        heading: "Wallet Settings",
        path: "/admin/wallet-settings",
        icon: <TbWallet size={18} />,
      },
      {
        key: "sub-admins",
        label: "Sub-Admins",
        heading: "Sub-Admins",
        path: "/admin/sub-admins",
        icon: <TbUsersGroup size={18} />,
      },
      {
        key: "media-management",
        label: "Media Management",
        heading: "Media Management",
        icon: <TbPhoto size={18} />,
        children: [
          {
            key: "slider-banners",
            label: "Slider Banners",
            heading: "Slider Banners",
            path: "/admin/slider",
            icon: <TbSlideshow size={18} />,
          },
          {
            key: "image-gallery",
            label: "Image Gallery",
            heading: "Image Gallery",
            path: "/admin/gallery",
            icon: <TbPhoto size={18} />,
          },
          {
            key: "videos",
            label: "Videos",
            heading: "Videos",
            path: "/admin/video",
            icon: <TbPlayerPlay size={18} />,
          },
          {
            key: "training-videos",
            label: "Training Content",
            heading: "Training Content",
            path: "/admin/training-videos",
            icon: <TbPlayerPlay size={18} />,
          },
          {
            key: "news",
            label: "News",
            heading: "News",
            path: "/admin/news",
            icon: <TbNews size={18} />,
          },
          {
            key: "pdfs",
            label: "PDF Documents",
            heading: "PDF Documents",
            path: "/admin/pdfs",
            icon: <TbFileTypePdf size={18} />,
          },
        ],
      },
      {
        key: "community-management",
        label: "Community Management",
        heading: "Community Management",
        icon: <TbHierarchy size={18} />,
        children: [
          {
            key: "communities",
            label: "Communities",
            heading: "Communities",
            path: "/admin/communities",
            icon: <TbHierarchy size={18} />,
          },
          {
            key: "vansh",
            label: "Vansh",
            heading: "Vansh",
            path: "/admin/vansh",
            icon: <TbHierarchy size={18} />,
          },
          {
            key: "kul",
            label: "Kul",
            heading: "Kul",
            path: "/admin/kul",
            icon: <TbHierarchy size={18} />,
          },
          {
            key: "khamp",
            label: "Khamp",
            heading: "Khamp",
            path: "/admin/khamp",
            icon: <TbHierarchy size={18} />,
          },
          {
            key: "gotra",
            label: "Gotra",
            heading: "Gotra",
            path: "/admin/gotra",
            icon: <TbHierarchy size={18} />,
          },
        ],
      },
      {
        key: "location-management",
        label: "Location Management",
        heading: "Location Management",
        icon: <TbMapPin size={18} />,
        children: [
          {
            key: "countries",
            label: "Countries",
            heading: "Countries",
            path: "/admin/countries",
            icon: <TbMapPin size={18} />,
          },
          {
            key: "states",
            label: "States",
            heading: "States",
            path: "/admin/states",
            icon: <TbMapPin size={18} />,
          },
          {
            key: "districts",
            label: "Districts",
            heading: "Districts",
            path: "/admin/districts",
            icon: <TbMapPin size={18} />,
          },
          {
            key: "villages",
            label: "Villages",
            heading: "Villages",
            path: "/admin/villages",
            icon: <TbMapPin size={18} />,
          },
          {
            key: "pending-location-approvals",
            label: "Pending Approvals",
            heading: "Pending Approvals",
            path: "/admin/location-pending-approvals",
            icon: <TbMapPin size={18} />,
          },
        ],
      },
    ],
  },
  {
    key: "users-list",
    label: "Users List",
    heading: "Users List",
    path: "/admin/users-list",
    icon: <FaRegUser size={18} />,
  },
  {
    key: "family",
    label: "Family",
    heading: "Family",
    icon: <TbHierarchy size={18} />,
    children: [
      {
        key: "family-management",
        label: "Family Management",
        heading: "Family Management",
        path: "/admin/family",
        icon: <TbHierarchy size={18} />,
      },
      {
        key: "matrimonial",
        label: "Matrimonial Applications",
        heading: "Matrimonial Applications",
        path: "/admin/matrimonial/applications",
        icon: <TbUsers size={18} />,
      },
    ],
  },
  {
    key: "donations",
    label: "Donations",
    heading: "Donations",
    icon: <TbHeartHandshake size={18} />,
    children: [
      {
        key: "donation-buttons",
        label: "Donation Buttons",
        heading: "Donation Buttons",
        path: "/admin/donation/buttons",
        icon: <TbDeviceGamepad2 size={18} />,
      },
      {
        key: "donation-requests",
        label: "Donation Requests",
        heading: "Donation Requests",
        path: "/admin/donation/requests",
        icon: <TbDeviceGamepad2 size={18} />,
      },
    ],
  },
  {
    key: "wallet-finance",
    label: "Wallet & E-PIN",
    heading: "Wallet & E-PIN",
    icon: <TbWallet size={18} />,
    children: [
      {
        key: "manage-wallets",
        label: "Manage Wallets",
        heading: "Manage Wallets",
        path: "/admin/wallet-management/manage",
        icon: <TbWallet size={18} />,
      },
      {
        key: "wallet-details",
        label: "Wallet Details",
        heading: "Wallet Details",
        path: "/admin/wallet-management/details",
        icon: <TbWallet size={18} />,
      },
      {
        key: "member-balance",
        label: "Member Balance",
        heading: "Member Balance",
        path: "/admin/wallet-management/member-balance",
        icon: <TbWallet size={18} />,
      },
      {
        key: "transfer-report",
        label: "Transfer Report",
        heading: "Transfer Report",
        path: "/admin/wallet-management/transfer-report",
        icon: <TbWallet size={18} />,
      },
      {
        key: "withdrawal-requests",
        label: "Withdrawal Requests",
        heading: "Withdrawal Requests",
        path: "/admin/wallet-management/withdrawal-requests",
        icon: <TbWallet size={18} />,
      },
      {
        key: "epin-management",
        label: "E-PIN Management",
        heading: "E-PIN Management",
        path: "/admin/epins",
        icon: <TbKey size={18} />,
      },
    ],
  },
  {
    key: "commission-ranks",
    label: "Commission & Ranks",
    heading: "Commission & Ranks",
    icon: <TbWallet size={18} />,
    children: [
      {
        key: "team-explorer",
        label: "Team Explorer",
        heading: "Team Explorer",
        path: "/admin/team",
        icon: <TbUsersGroup size={18} />,
      },
      {
        key: "referral-analytics",
        label: "Referral Analytics",
        heading: "Referral Analytics",
        path: "/admin/referrals",
        icon: <TbUsers size={18} />,
      },
      {
        key: "designations",
        label: "Designations",
        heading: "Designations",
        path: "/admin/designations",
        icon: <TbUsers size={18} />,
      },
      {
        key: "ranks",
        label: "Rank Management",
        heading: "Rank Management",
        path: "/admin/ranks",
        icon: <TbUsers size={18} />,
      },
      {
        key: "level-commission",
        label: "Level Commission",
        heading: "Level Commission",
        path: "/admin/level-commission",
        icon: <TbWallet size={18} />,
      },
      {
        key: "commission-payout",
        label: "Commission Payout",
        heading: "Commission Payout Management",
        path: "/admin/commission-payout",
        icon: <TbWallet size={18} />,
      },
    ],
  },
  {
    key: "sbi-analysis",
    label: "SBI Analysis",
    heading: "SBI Analysis",
    icon: <TbUsers size={18} />,
    children: [
      {
        key: "appointments-list",
        label: "Appointment Management",
        heading: "Appointment Management",
        path: "/admin/appointments",
        icon: <TbUsers size={18} />,
      },
      {
        key: "slot-management",
        label: "Slot Management",
        heading: "Slot Management",
        path: "/admin/slots",
        icon: <TbUsers size={18} />,
      },
      {
        key: "sbi-pro-sessions",
        label: "SBI PRO Sessions",
        heading: "SBI PRO Sessions",
        path: "/admin/sbi-pro-sessions",
        icon: <TbUsers size={18} />,
      },
      {
        key: "counselling-sessions",
        label: "Counselling Sessions",
        heading: "Counselling Sessions",
        path: "/admin/counselling-sessions",
        icon: <TbUsers size={18} />,
      },
    ],
  },
];
export default AdminSidebarItems;
