export const SBI_PRO_ASSIGNED_REQUEST = "SBI_PRO_ASSIGNED_REQUEST";
export const SBI_PRO_ASSIGNED_SUCCESS = "SBI_PRO_ASSIGNED_SUCCESS";
export const SBI_PRO_ASSIGNED_ERROR = "SBI_PRO_ASSIGNED_ERROR";

export const SBI_PRO_SESSION_REQUEST = "SBI_PRO_SESSION_REQUEST";
export const SBI_PRO_SESSION_SUCCESS = "SBI_PRO_SESSION_SUCCESS";
export const SBI_PRO_SESSION_ERROR = "SBI_PRO_SESSION_ERROR";

export const SBI_PRO_UPLOAD_REQUEST = "SBI_PRO_UPLOAD_REQUEST";
export const SBI_PRO_UPLOAD_SUCCESS = "SBI_PRO_UPLOAD_SUCCESS";
export const SBI_PRO_UPLOAD_ERROR = "SBI_PRO_UPLOAD_ERROR";

export const SBI_PRO_SUBMIT_REQUEST = "SBI_PRO_SUBMIT_REQUEST";
export const SBI_PRO_SUBMIT_SUCCESS = "SBI_PRO_SUBMIT_SUCCESS";
export const SBI_PRO_SUBMIT_ERROR = "SBI_PRO_SUBMIT_ERROR";

export const SBI_PRO_PENDING_VERIFICATION_REQUEST = "SBI_PRO_PENDING_VERIFICATION_REQUEST";
export const SBI_PRO_PENDING_VERIFICATION_SUCCESS = "SBI_PRO_PENDING_VERIFICATION_SUCCESS";
export const SBI_PRO_PENDING_VERIFICATION_ERROR = "SBI_PRO_PENDING_VERIFICATION_ERROR";

export const SBI_PRO_VERIFY_REQUEST = "SBI_PRO_VERIFY_REQUEST";
export const SBI_PRO_VERIFY_SUCCESS = "SBI_PRO_VERIFY_SUCCESS";
export const SBI_PRO_VERIFY_ERROR = "SBI_PRO_VERIFY_ERROR";

export const SBI_PRO_REPORTS_REQUEST = "SBI_PRO_REPORTS_REQUEST";
export const SBI_PRO_REPORTS_SUCCESS = "SBI_PRO_REPORTS_SUCCESS";
export const SBI_PRO_REPORTS_ERROR = "SBI_PRO_REPORTS_ERROR";
export const SBI_PRO_CLIENT_REPORTS_REQUEST = "SBI_PRO_CLIENT_REPORTS_REQUEST";
export const SBI_PRO_CLIENT_REPORTS_SUCCESS = "SBI_PRO_CLIENT_REPORTS_SUCCESS";
export const SBI_PRO_CLIENT_REPORTS_ERROR = "SBI_PRO_CLIENT_REPORTS_ERROR";
