/**
 * Standardized error codes for appointment APIs
 */
module.exports = {
  APPOINTMENT_ONE_BOOKING_PER_DATE: "APPOINTMENT_ONE_BOOKING_PER_DATE",
  APPOINTMENT_SELF_BOOKING: "APPOINTMENT_SELF_BOOKING",
  APPOINTMENT_LIMIT_REACHED: "APPOINTMENT_LIMIT_REACHED",
  APPOINTMENT_PROGRESSION_REQUIRED: "APPOINTMENT_PROGRESSION_REQUIRED",
  APPOINTMENT_HOLDER_OFFLINE: "APPOINTMENT_HOLDER_OFFLINE",
  APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
  APPOINTMENT_ALREADY_PROCESSED: "APPOINTMENT_ALREADY_PROCESSED",
  APPOINTMENT_CANCEL_TOO_LATE: "APPOINTMENT_CANCEL_TOO_LATE",
  APPOINTMENT_INVALID_RATING: "APPOINTMENT_INVALID_RATING",
  APPOINTMENT_OFFLINE_BLOCKED: "APPOINTMENT_OFFLINE_BLOCKED",
  FREE_APPOINTMENT_LIMIT_REACHED: "FREE_APPOINTMENT_LIMIT_REACHED",
  APPOINTMENT_INVALID_SLOT_TIME: "APPOINTMENT_INVALID_SLOT_TIME",
  APPOINTMENT_PENDING_EXISTS_FOR_DESIGNATION: "APPOINTMENT_PENDING_EXISTS_FOR_DESIGNATION",
  APPOINTMENT_ONE_TIME_ONLY_FOR_DESIGNATION: "APPOINTMENT_ONE_TIME_ONLY_FOR_DESIGNATION",
  APPOINTMENT_PENDING_EXISTS_WITH_SAME_HOLDER: "APPOINTMENT_PENDING_EXISTS_WITH_SAME_HOLDER",
  SLOT_INACTIVE: "SLOT_INACTIVE",
  SLOT_TIME_OVERLAP: "SLOT_TIME_OVERLAP",
};
